INSERT INTO ROLE VALUES(1, 'ADMIN');
INSERT INTO ROLE VALUES(2, 'MODER');
INSERT INTO ROLE VALUES(3, 'STUDENT');
INSERT INTO ROLE VALUES(4, 'LECTURER');
INSERT INTO ROLE VALUES(5, 'USER');


INSERT INTO APP_USER VALUES (1, null,null ,'Root',null ,'Root','$2a$10$jg8TvY9jouyugViXP4lC0eBU/GLu2iBcngK8vOd0MQ5qlbkSklJIG','admin');

INSERT INTO APP_USER_ROLES VALUES (1, 1)